author: Patrick Hilhorst (s4577434)
title: Title
subtitle: Subtitle
date: today

documentclass: tufte-handout
papersize: a4
numbersections: true
toc: true

# Stop TOC from ragging
classoption: "marginals=raggedouter,notoc"


# Convert these div classes to latex environments:
div-conversions:
    # Figure envs
    figure: "figure"
    sidebar: "marginfigure"
    marginfigure: "marginfigure"
    widefigure: "figure*"

    # Text envs
    twocolumn: "widetwocolumn"
    fullwidth: "fullwidth"
    landscape: "tufte-landscape"

# Options for pandoc-citeproc:
bibliography:
    - bibliography.bib
# Uncomment for ACM SIGGRAPH citations:
citation-style: ACM-SIGGRAPH
# Uncomment for IEEE-Style citations:
# citation-style: IEEE
# For more styles, see https://www.zotero.org/styles/
